### PR TITLE
Added info in contributing.md

### PR DESCRIPTION
**Pull request by iamatifmoin**
Added my details in the contributing.md file

### CODE REVIEW

**Comment by py3-coder** [comment]
Need to do contribution in any domain.
Not able to find any contribution??

**Comment by iamatifmoin** [comment]
> Need to do contribution in any domain. Not able to find any contribution??

I have written a solution code for the famous Tower Of Hanoi solution. 
Patiently waiting for your approval @py3-coder

**Comment by py3-coder** [comment]
Hey @iamatifmoin . Got it Man..
PR accepted @iamatifmoin .
Successfully merged to HacktoberFest_22 repo.
🚀🚀👍

**Comment by iamatifmoin** [comment]
> Hey @iamatifmoin . Got it Man.. PR accepted @iamatifmoin . Successfully merged to HacktoberFest_22 repo. rocketrocket+1

@py3-coder Thankyou!

**Pull request merged**
