### PR TITLE
Student Teacher Information

### PR DESCRIPTION
**Pull request by Souvik2376**

### CODE REVIEW

**Comment by py3-coder** [comment]
Read the Readme.md  file of Java as well as Python.
Guideline how to add java and python file read it again.

**Comment by py3-coder** [comment]
Read the Readme.md  file of Java as well as Python.
Guideline how to add java and python file read it again 
PR accepted @Souvik2376 
Need to Star this repo incase not done.
Just Update the required will merge to main
🚀🚀👍

**Comment by Souvik2376** [comment]
I already update readme.md.....this is second time for me

**Comment by py3-coder** [comment]
> 

Just Read the Readme.md inside java folder and in python folder too.

**Pull request merged**
