### PR TITLE
BinarySearch.py

### PR DESCRIPTION
**Pull request by MauryaNitish65**

### CODE REVIEW

**Comment by py3-coder** [comment]
Need fix . Read README.file Correctly and update to [CONTRIBUTING.md](https://github.com/py3-coder/Hacktober_Repo_22/blob/main/CONTRIBUTING.md) your profile Details.

**Comment by MauryaNitish65** [comment]
Fixed the code according to requirement

**Comment by MauryaNitish65** [comment]
Fixed According to Need

**Comment by MauryaNitish65** [comment]
Please Check

**Comment by py3-coder** [comment]
Welcome to Open Source Contribution.
PR accepted @MauryaNitish65  🚀🚀👍

**Comment by MauryaNitish65** [comment]
this code submission is excluded 
Can you please tell why is it happening?

**Pull request merged**
