### PR TITLE
created fibbonacci.cpp

### PR DESCRIPTION
**Pull request by arjsivam**
Added the fibbonaci code.

### CODE REVIEW

**Comment by py3-coder** [comment]
Update the [CONTRIBUTING.md](https://github.com/py3-coder/Hacktober_Repo_22/blob/main/CONTRIBUTING.md) 
Read the README.md file again.
Update it in this PR only.
No need to create new PR @arjsivam 
Update it asap .Will Proceed for further verification.

**Comment by arjsivam** [comment]
> Update the [CONTRIBUTING.md](https://github.com/py3-coder/Hacktober_Repo_22/blob/main/CONTRIBUTING.md) Read the README.md file again. Update it in this PR only. No need to create new PR @arjsivam Update it asap .Will Proceed for further verification.

Done kindly merge my request.

**Comment by py3-coder** [comment]
PR accepted @arjsivam .
Successfully merged to HacktoberFest_22 repo.
🚀🚀👍

**Comment by py3-coder** [comment]
need fix found in diff. PR.

**Pull request merged**
