### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by dhruvaop**

### CODE REVIEW

**Comment by py3-coder** [comment]
Not able to find Contribution File.
What Contribution you had done. Kindly elaborate??

**Comment by dhruvaop** [comment]
Screenshot (2)

**Comment by dhruvaop** [comment]
<<<<<<< patch-1

--------
NAME : Dhruva Bhattacharya <br>
GITHUB : github.com/dhruvaop <br>
INSTITUTE/COMPANY : GGITS <br>
DOMAIN/LANGUGAE : C++, Python, C# <br>
--------

=======
--------------
NAME : Ritik kumar <br>
GITHUB : https://github.com/ritik1123 <br>
INSTITUTE/COMPANY : Galgotias University <br>
DOMAIN/LANGUGAE : Web Development/C++ <br>
-----------

-----------
NAME :  Lakshay Tyagi <br>
GITHUB :  [imlakshay08](https://github.com/imlakshay08) <br>
INSTITUTE/COMPANY : Maharshi Dayanand University <br>
DOMAIN: Java <br>
-----------
--------------
NAME :  Avid Coder<br>
GITHUB :  github.com/qyu4x<br>
INSTITUTE/COMPANY : NULL<br>
DOMAIN/LANGUGAE : JS<br>
------------
>>>>>>> main

### In COUNTRIBUTORS.md

**Comment by py3-coder** [comment]
I am asking about in which domain you have contributed.?
As per my repo norms you have to contribute to at least one domain/language
Then only I will able to accept under hactoberfest label.
Hope You get it.
Do some contribution . Will happily accept you PR.

**Pull request closed without merging**
