### PR TITLE
Online University-Management-System

### PR DESCRIPTION
**Pull request by Swayms-stack**
The online University Management System Project In Java is a completely useful Java project which incorporates data about schools, colleges, and schools overall. It was made for the college and its partnered establishments to lead, screen, and dissect confounded exercises like brought together affirmation, unified assessments, and considerably more.

### CODE REVIEW

**Comment by py3-coder** [comment]
Happy to such good Project . But there you need to update the contribution.md file with you profile details.
Just Do that in same PR. or create new 
will verify it for further Process .

**Comment by Swayms-stack** [comment]
I did.
Could you please check  ?

**Comment by py3-coder** [comment]
PR accepted @Swayms-stack .
Successfully merged to HacktoberFest_22 repo.
🚀🚀👍

**Comment by Swayms-stack** [comment]
Thanks a lot.

**Pull request merged**
