### PR TITLE
factorial of  a  number  using  resursion

### PR DESCRIPTION
**Pull request by dev-divyansh**
please merge  this pr

under lable  hacktoberfest , i am a  contributor for  hacktoberfest

### CODE REVIEW

**Comment by py3-coder** [comment]
Update the [CONTRIBUTING.md](https://github.com/py3-coder/Hacktober_Repo_22/blob/main/CONTRIBUTING.md) 
Read the README.md file again.
Update it in this PR only.
No need to create new PR @dev-divyansh 
Update it asap .Will Proceed for further verification.

**Comment by dev-divyansh** [comment]
I have updated  in my patch 1 branch

**Comment by dev-divyansh** [comment]
Please check it @py3-coder

**Comment by py3-coder** [comment]
image
@dev-divyansh 
How you update your details .
Is this is the way? Don't append in between others data.
Please how can I merge this??
Check the template once again and append your data at the end and anywhere.
I hope you can get it.

**Comment by py3-coder** [comment]
Update it again.
Will verify and then add.

**Comment by dev-divyansh** [comment]
please recheck it @py3-coder

**Pull request closed without merging**
