### PR TITLE
Email validation

### PR DESCRIPTION
**Pull request by Shansince2k3**
Check the email is valid or not using the regex module

### CODE REVIEW

**Comment by py3-coder** [comment]
Update the [CONTRIBUTING.md](https://github.com/py3-coder/Hacktober_Repo_22/blob/main/CONTRIBUTING.md) 
Read the README.md file again.
Update it in this PR only.
No need to create new PR @Shansince2k3.
Update it asap .Will Proceed for further verification.

**Comment by Shansince2k3** [comment]
Completed 😊,so accepted the pr request

**Comment by Shansince2k3** [comment]
> Update the [CONTRIBUTING.md](https://github.com/py3-coder/Hacktober_Repo_22/blob/main/CONTRIBUTING.md) 
> Read the README.md file again.
> Update it in this PR only.
> No need to create new PR @Shansince2k3.
> Update it asap .Will Proceed for further verification.

Bro i fix it 😇. ACCEPTED THE PR REQUEST

**Comment by py3-coder** [comment]
PR accepted @Shansince2k3 
Successfully merged to HacktoberFest_22 repo.
Make sure from next follow the README.md file steps properly.
Hope you will not repeat.
🚀🚀👍

**Pull request merged**
