### PR TITLE
BubbleSort 

### PR DESCRIPTION
**Pull request by arka9088**

### CODE REVIEW

**Comment by py3-coder** [comment]
Follow the template to update in Contributing.md file
@arka9088 
Make it figure out. Update it

**Comment by arka9088** [comment]
Hi i updated

**Comment by py3-coder** [comment]
Bug Found !... Close this PR and create New PR.
Update the [CONTRIBUTING.md](https://github.com/py3-coder/Hacktober_Repo_22/blob/main/CONTRIBUTING.md) 
Read the README.md file again.
@arka9088

**Comment by py3-coder** [comment]
Hey @arka9088 .
Just Reopen it.
We have changed the process. Due to common issues.

**Pull request closed without merging**
