### PR TITLE
Create liner_regression.py

### PR DESCRIPTION
**Pull request by IshaSah**
This program is the implementation of linear regression in Python programming language.

### CODE REVIEW

**Comment by py3-coder** [comment]
Update the [CONTRIBUTING.md](https://github.com/py3-coder/Hacktober_Repo_22/blob/main/CONTRIBUTING.md) 
Read the README.md file again.
Update it in this PR only.
No need to create new PR @IshaSah 
Update it asap .Will Proceed for further verification.

**Comment by IshaSah** [comment]
done the necessary changes.Please verify.

**Comment by py3-coder** [comment]
Verified @IshaSah .
PR accepted @IshaSah 
Successfully merged to HacktoberFest_22 repo.
🚀🚀👍

**Comment by IshaSah** [comment]
Thanks a lot.

**Pull request merged**
