### PR TITLE
Create DSA android fingerprint.java

### PR DESCRIPTION
**Pull request by Sanu1999**

### CODE REVIEW

**Comment by Mainakdey1** [comment]
Maybe use your own keys for authentication in-module? @Sanu1999

**Comment by Sanu1999** [comment]
I had changed

**Comment by Sanu1999** [comment]
> Maybe use your own keys for authentication in-module? @Sanu1999 

Updated
..

**Comment by py3-coder** [comment]
@Sanu1999 Can please explain about your Project.?
Seems quite interesting. 
what is does and what complete tech-stack.
Don't Worry about label will surely marge in Repo with hacktoberfest tag?

**Comment by Mainakdey1** [comment]
> > Maybe use your own keys for authentication in-module? @Sanu1999 
> 
> Updated
> ..

Thank you I modified my comment.

**Comment by py3-coder** [comment]
Waiting for your response @Sanu1999 ?
Not merged into main
PR accepted @Sanu1999 
🚀🚀👍

**Review by Sanu1999 — COMMENTED** [review]
This is a DSA algorithm for the android fingerprint encryption security. it works with android 6 and above. In order to authenticate users using fingerprint sensors we need the instance of Fingerprint Manager class and call the authenticate() method. Also, we should take care of the devices that must have fingerprint sensors. We will use generateKey() method which will generate an encryption key that is stored securely on the device, we will also use cipherInit() method which initialized the cipher that will be used to create the encrypted FingerprintManager.

**Comment by py3-coder** [comment]
Ok , @Sanu1999  have you implemented  in real devices. This algorithm is general algorithm or it developed by you??
Need more info  just asking for knowledge point of view.?

**Comment by py3-coder** [comment]
PR accepted @Sanu1999 
Successfully merged to HacktoberFest_22 repo.
Need to Star this repo incase not done.
🚀🚀👍

**Pull request merged**
