### PR TITLE
Added Code Template for Merge Sort

### PR DESCRIPTION
**Pull request by sayskar500**

### CODE REVIEW

**Comment by sayskar500** [comment]
Added username details afterwards in CONTRIBUTING.md file

**Comment by py3-coder** [comment]
Reason Behind Updating Full CONTRIBUTION.md file.?

**Comment by py3-coder** [comment]
Kindly Review the updated CONTRIBUTION.md made by you change is good but must have same pattern through out file.
Make it clear will surely merge.
@sayskar500

**Comment by py3-coder** [comment]
Good to see such standard way of representation ~ update in contribution.md file
Need you help in some small stuff.
If you can then it would be appreciable.
@sayskar500 .

**Comment by py3-coder** [comment]
PR accepted @sayskar500.
Successfully merged to HacktoberFest_22 repo.
🚀🚀👍

**Comment by sayskar500** [comment]
sure @py3-coder where should we converse for furthur information?

**Pull request merged**
