### PR TITLE
WA automation

### PR DESCRIPTION
**Pull request by ankushKun**
Added a Selenium script to automatically check for new messages from a specific contact and respond with a set of predefined responses.

### CODE REVIEW

**Comment by py3-coder** [comment]
Hey @ankushKun  . There is change in our guideline Kindly delete the update in CONTRIBUTION.md.
Will happy to see the updated one. 
Don't worry about acceptance.

**Comment by ankushKun** [comment]
Hi @py3-coder, I have removed the update from CONTRIBUTION.md

Thank you

**Comment by py3-coder** [comment]
Thanks @ankushKun .
PR accepted @ankushKun.
Successfully merged to HacktoberFest_22 repo.
🚀🚀👍

**Comment by Mainakdey1** [comment]
@ankushKun nice lol.

**Pull request merged**
