### PR TITLE
Added  Java Code 

### PR DESCRIPTION
**Pull request by king-rohit777**

### CODE REVIEW

**Comment by py3-coder** [comment]
@king-rohit777  Just Update it once more , Due to some issue We have changed or guidelines.
Just need some update.
Delete the Contribution.md update

**Comment by king-rohit777** [comment]
> @king-rohit777 Just Update it once more , Due to some issue We have changed or guidelines. Just need some update. Delete the Contribution.md update

Done

**Comment by py3-coder** [comment]
Hey @king-rohit777  .This conflict is from your side I can't fix it.
Just do one thing.
delete the contribution.md from your file.
Or If  are facing issue then also just make new PR.

**Comment by king-rohit777** [comment]
> Hey @king-rohit777 .This conflict is from your side I can't fix it. Just do one thing. delete the contribution.md from your file. Or If are facing issue then also just make new PR.

Created a new PR
Pls approve: https://github.com/py3-coder/Hacktober_Repo_22/pull/232

**Pull request closed without merging**
