### PR TITLE
Laptop Price Prediction WebApp

### PR DESCRIPTION
**Pull request by ankitkumar174**
Laptop price prediction Web app, this folder contain all the files which is useful for making or deploying the laptop price prediction model into web app. 
This project is build by using Machine Learning and streamlit.

### CODE REVIEW

**Comment by Mainakdey1** [comment]
Yo, are you using a weighted model to predict prices? like ram takes precedence over display etc?

**Comment by py3-coder** [comment]
Hey @ankitkumar174  Everything is  Ok. But you had committed the project to wrong dir.
See there is one special dir for Data Science . Read the Readme file there how to contribute any ml project.
Just follow those guideline.
Will happy to see update PR.

**Comment by ankitkumar174** [comment]
Yes, it is easily run on RAM because its a Machine Learning model its processing time or storage are less and the dataset used in this model is easily managed by ram.
We need GPU for Deep Learning models.

**Comment by ankitkumar174** [comment]
> Hey @ankitkumar174  Everything is  Ok. But you had committed the project to wrong dir.
> See there is one special dir for Data Science . Read the Readme file there how to contribute any ml project.
> Just follow those guideline.
> Will happy to see update PR.
> 

Ok, i will update the PR and changed the project dir.

**Comment by ankitkumar174** [comment]
> Hey @ankitkumar174  Everything is  Ok. But you had committed the project to wrong dir.
> See there is one special dir for Data Science . Read the Readme file there how to contribute any ml project.
> Just follow those guideline.
> Will happy to see update PR.
> 

I have made the changes of my projects according to your guidelines.

**Pull request closed without merging**
