### PR TITLE
Added the Quick Sort Program in C++

### PR DESCRIPTION
**Pull request by mananaggarwal2001**

### CODE REVIEW

**Comment by py3-coder** [comment]
Update the [CONTRIBUTING.md](https://github.com/py3-coder/Hacktober_Repo_22/blob/main/CONTRIBUTING.md) 
Read the README.md file again.
Update it in this PR only.
No need to create new PR @
Update it asap .Will Proceed for further verification.

**Comment by py3-coder** [comment]
Don't Update in between other data . You need to add your data at end ..not in between other ..

**Comment by py3-coder** [comment]
image

See what you had done @mananaggarwal2001 ..

**Comment by mananaggarwal2001** [comment]
This is not  the invalid data its  the merge conflict need to resolve

**Comment by mananaggarwal2001** [comment]
resloved the merge conflct remove the invalid tag and merge my file

**Comment by mananaggarwal2001** [comment]
I have added only my data and this is the merge conflict that I have resolved this problem is automatically created it;s not my fault

**Comment by mananaggarwal2001** [comment]
Fixed merge conflict

**Comment by py3-coder** [comment]
PR accepted @mananaggarwal2001 
Successfully merged to HacktoberFest_22 repo.
🚀🚀👍

**Comment by py3-coder** [comment]
Accepted but it still contains bug @mananaggarwal2001 .
Will fix it out by myself.

**Comment by mananaggarwal2001** [comment]
okkk

**Pull request merged**
